### ISSUE TITLE
Talk to NPC afer a long walk

### ISSUE THREAD

**Issue by pejoso** [wrathion-classic/Wrathion#1]
**Description:**
So, if talk to a NPC after run for wilhe, the frist time u try to slect any options Like, Train or something else, de option does not work, so u have to untarget the NPC and try talk again, and then its works

**How to reproduce:**
Walk in any city and then try to talk with any NPC with dialog or something else

**How it should work:**
U should be able to select the option in the first time.

**Comment by wrathion-classic** [comment]
That might be creature related. Can you specify the last npc you used that did that?

**Comment by pejoso** [comment]
Cokking trainer
Fisshing 
Classa Trainer

Basicly all of them Teste on silvermon

**Comment by pejoso** [comment]
Fisshing 
Classa Trainer

Basicly all of them

**Comment by pejoso** [comment]
https://youtu.be/PCeZ_TsjvMk

Also happened   with Class traines, Cokinking,  Fising, Paly,  Eng, etc

**Comment by wrathion-classic** [comment]
Cannot reproduce the issue. It could be an addon issue here.
