### ISSUE TITLE
Can't Mark of the Wild (druid buff) when there is a scroll buff

### ISSUE THREAD

**Issue by pejoso** [wrathion-classic/Wrathion#10]
**Description:**
Can't Mark of the Wild (druid buff) when there is a scroll buff

**How to reproduce:**
Buff yoursel with any scroll buf and then try buff Mark of the Wild. will show a massage "A porwfull buff is active"

**How it should work:**
U should be able to buff your self with one of the scoll buffs up

**Comment by wrathion-classic** [comment]
It's working as intended. You can't cast Motw because the scroll buff has higher stamina stat than the Motw spell.
