### ISSUE TITLE
Second Slot (Personal Bank) does not work

### ISSUE THREAD

**Issue by pejoso** [wrathion-classic/Wrathion#11]
**Description:**
Second Slot (Personal Bank) does not work
![image](https://github.com/user-attachments/assets/57fccafb-31c1-4e2d-bfd0-384fddd8a7ba)

**How to reproduce:**
Buy the slot and try one bag there

**How it should work:**
Should work

**Comment by wrathion-classic** [comment]
Invalid. 
![image](https://github.com/user-attachments/assets/b4f5776d-83ad-4f94-a656-ace7430cec1e)

**Comment by pejoso** [comment]
Not sure if its a addon BUG

![image](https://github.com/user-attachments/assets/cbea3d8a-5bdf-4ccf-aa7a-b341584750b4)
![image](https://github.com/user-attachments/assets/84dccbd6-27e3-440f-a1b3-382613e46bd5)
![image](https://github.com/user-attachments/assets/e9ae65a4-299c-48ee-95e1-398e28f913b8)
![image](https://github.com/user-attachments/assets/ae66e367-88e0-4fc2-b469-cfbf98ca50b2)
![image](https://github.com/user-attachments/assets/3e013d78-0326-4644-9da0-1fed6a703851)
![image](https://github.com/user-attachments/assets/208cf805-ed4e-49c1-93b5-fc97fa824cc0)
