### ISSUE TITLE
The Kessel Run

### ISSUE THREAD

**Issue by ovidas89** [wrathion-classic/Wrathion#12]
**Description:**
Issue with the following quest : 
https://www.wowhead.com/wotlk/quest=9663/the-kessel-run

**How to reproduce:**
Go to NPC accept quest and try to leave the quest giver compound, as soon as you reach the pathway with the mount you get dismounted.
![image](https://github.com/user-attachments/assets/05cca76c-575e-4edd-9f1c-fa3597b3f01a)
Tried to do as RXP mentions, no matter where I try to cross , as soon as I get some range from the quest giver , I get dismounted.

**How it should work:**
Loaned mount should work for 15min ( as long as you don't go into water or cast any spells or go into hostile areas)

**Comment by wrathion-classic** [comment]
Fixed
