### ISSUE TITLE
Disenchant Loot tables are wrong

### ISSUE THREAD

**Issue by Jinteki01** [wrathion-classic/Wrathion#13]
**Description:**
Disenchanting items sometimes (usually most of the time) gives enchanting materials higher level that what should be available from the item. For example I disenchanted multiple level 5-10 items and got soul dust. All the low level greens I have disenchanted did not give a single Magic Essence, only Astral Essence or higher quality. 

**How to reproduce:**
Gather a bunch of green items ranging from level 5-20.
Disenchant them and check the materials your receive.

**How it should work:**
The loot tables should be like this https://www.wow-professions.com/wotlk/disenchanting-tables-wotlk-classic
https://wowwiki-archive.fandom.com/wiki/Disenchanting_tables?oldid=2486849

**Comment by wrathion-classic** [comment]
Fixed.
