### ISSUE TITLE
Paladin seal and item compare

### ISSUE THREAD

**Issue by msaramon** [wrathion-classic/Wrathion#14]
**Description:**
![WoWScrnShot_112024_175417](https://github.com/user-attachments/assets/5dff1aaf-d1dc-4878-a745-8701d97d2649)
paladin has 2 seal of righteousness.
some comprison of 2 items does not count,like screen shot.

**How to reproduce:**

**How it should work:**

**Comment by wrathion-classic** [comment]
The double seal has been fixed.

About the item comparison that's a classic client thing, you'd know if you've played on classic. 
If you want to compare items you can download an addon.
