### ISSUE TITLE
DC  when   I change  any   rank on Guild control

### ISSUE THREAD

**Issue by pejoso** [wrathion-classic/Wrathion#15]
**Description:**
Well,  I'm tryinto to set up the guild ranks , and   when  I change something  and click on acpet,   I got DC
![image](https://github.com/user-attachments/assets/5646c47d-64b3-436d-abac-748a695b9556)
![image](https://github.com/user-attachments/assets/ea20ef28-8307-4251-be0b-c892ad9bf1b0)
![image](https://github.com/user-attachments/assets/15f868d4-8024-404c-bfc1-4cee4be9a8af)
![image](https://github.com/user-attachments/assets/a03a001d-5929-471f-9dd5-dddd6e292977)

**How to reproduce:**
Creat a guild and   try to give permision to deposit items

**How it should work:**
Not get  DC

**Comment by wrathion-classic** [comment]
Fixed.
