### ISSUE TITLE
Zeppelin Master not intecatable.

### ISSUE THREAD

**Issue by Pepsi-Coke** [wrathion-classic/Wrathion#16]
**Description:**
I tried to interact/talk to the Zeppelin Master outside of Ogrimmar to check "Where is the Zeppelin now?" but the NPC did not respond or react to it. I think none of the Zeppelin masters is working

**How to reproduce:**
Talking to any Zeppelin master would be enough.

**How it should work:**
It should respond in a new window with the text.

**Comment by wrathion-classic** [comment]
Fixed.
