### ISSUE TITLE
Moving slow after being teleported while on a mount.

### ISSUE THREAD

**Issue by Pepsi-Coke** [wrathion-classic/Wrathion#17]
**Description:**
As the title states. If I get teleported or get teleported while on a mount. The character movement speed becomes very slow, slower than walking. The way to solve it is dismount, and mount again.

**How to reproduce:**
Taking a zeppelin, or just getting teleported by command while on a mount, (my guess is after changing map with a loading screen, the bug will appear)

**How it should work:**
After the process, movement speed should not be affected.

**Comment by wrathion-classic** [comment]
Fixed, it will be available next restart.
