### ISSUE TITLE
Razormaw doesn't move

### ISSUE THREAD

**Issue by Jinteki01** [wrathion-classic/Wrathion#18]
**Description:**
https://www.wowhead.com/wotlk/quest=9689/razormaw
Using the item for this quest spawns Razormaw correctly, but he never moves towards the bonfire after being spawned. Attempted twice and confirmed he spawned, but just stayed at the spawn point.

**How to reproduce:**
Obtain Razormaw quest and Bundle of Dragon Bones.
Use bones on the pyre at the top of the hill.
Observe Razormaw spawn far to the north.
Wait a few minutes as Razormaw does not move from the spawn point.

**How it should work:**
Razormaw should spawn in, then take some time to fly towards the pyre before engaging in combat with the player.

**Comment by Jinteki01** [comment]
Attempted again and moved down the hill towards Razormaw which finally triggered the pathing towards the pyre. It should start moving shortly after being summoned though. This was after approximately 5 minutes of watching Razormaw not move twice before.

**Comment by wrathion-classic** [comment]
Fixed, it will be applied on next restart.
