### ISSUE TITLE
Pilgram's bounty tables outside cities not working

### ISSUE THREAD

**Issue by Jinteki01** [wrathion-classic/Wrathion#20]
**Description:**
The tables outside the major cities are not working properly. No actions show for eating or passing the food when you sit in a chair.  You can still enter and exit the chairs properly though.
![WoWScrnShot_112424_051901](https://github.com/user-attachments/assets/79b06e9d-1fed-4b05-89b8-8b62289fc6b3)

**How to reproduce:**
Go to one of the tables outside a major city.
Enter the "vehicle" by clicking one of the chairs.
Observe there are no actions available in the vehicle.

**How it should work:**
There should be action buttons available to eat and pass food at each chair. Example image:
![WoWScrnShot_111812_125957_zpsd795c1dc](https://github.com/user-attachments/assets/6f497322-3acc-4790-851e-2d9735b65792)

**Comment by wrathion-classic** [comment]
Fixed
