### ISSUE TITLE
I'm able to lurnea recipe under the level recommendation

### ISSUE THREAD

**Issue by pejoso** [wrathion-classic/Wrathion#23]
**Description:**

https://youtu.be/DMBq0xNJ9Xs

I'm able to lurnea recipe under the level recommendation
![image](https://github.com/user-attachments/assets/6e9ce6d4-150e-4b3c-b9f3-5b923341d22b)
![image](https://github.com/user-attachments/assets/8df654e8-8cba-4441-8d66-8cb59b40e7ba)
![image](https://github.com/user-attachments/assets/33dbbb4b-5080-4b7c-a9cf-1fc534a1bd66)
![image](https://github.com/user-attachments/assets/ffebeb4c-86f1-4c9b-bb56-54ed8ef6d338)

**How to reproduce:**
Lv 28 or under,  with coking "300" and  try   learn [Recipe: Sagefish Delight] bought on  Thundr Bluf 

**How it should work:**
I   should't be able to do that

**Comment by wrathion-classic** [comment]
The level 30 is for the item, not the recipe.
