### ISSUE TITLE
Can't use Event Table

### ISSUE THREAD

**Issue by pejoso** [wrathion-classic/Wrathion#24]
**Description:**
Better show to you.

https://youtu.be/tqFmbFYCh9U

Is    not addon btw, I disable all   and until don't   show to me the options.

**How to reproduce:**
Go to the event table and  see the Action bars

**How it should work:**

https://www.youtube.com/watch?v=v34tRRCasF4&t=27s&ab_channel=Paper

**Comment by wrathion-classic** [comment]
Fixed
