### ISSUE TITLE
Cooking profession window bug

### ISSUE THREAD

**Issue by ovidas89** [wrathion-classic/Wrathion#25]
**Description:**
When opening Cooking profession, in the materials needed section, the amount of items is now showing. Tried disabling ElvUI and is  the same no amount showing;

**How to reproduce:**
![image](https://github.com/user-attachments/assets/34538078-8a58-40f8-86cb-8b710fed8585)

**How it should work:**
After gathering mats as shown in screenshot, they should be visible with amount needed and amount in inventory.

**Comment by wrathion-classic** [comment]
![image](https://github.com/user-attachments/assets/f5e860e1-f247-4b1c-9878-99b2e8f37149)

Couldn't reproduce, most likely an addon issue. Clear your cache and disable any addons and see if that helps.

**Comment by pejoso** [comment]
This is releted with the Actionatior addon. I had that also, Try to reinstal the addon. Also leatrix can cause that @ovidas89
