### ISSUE TITLE
Mobs do not attack after being polymorphed

### ISSUE THREAD

**Issue by Frostshake** [wrathion-classic/Wrathion#3]
**Description:**
After polymorphing a mob, they do no attack the caster (they still show as aggressive though, and follow me around). Happend at eastvale logging camp on wolves and bears. after this happening, the mob will never attack again, even if hitting them.
Note: just before this happening, Alistar did teleport me to a bg, not sure if this might be a factor.
Edit: if running away and resetting the mob, they go back to normal.
Edit2: looks to happen to all creatures with a melee attack, they appear to still be capable of ranged attacks (e.g defias smuggler)

**How to reproduce:**
- be mage
- cast polymorph on npc (in this case bear)
- do not attack npc, let polymorph run out
- npc now has the red aggressive glow on the portrait, and follows me around, however does not attack or cause damage

**How it should work:**
After polymorphing a mob, npc should be able to attack.

**Comment by wrathion-classic** [comment]
Fixed, it will be applied on next restart.
