### ISSUE TITLE
Barrens escort quest not showing as failed, npc not helping during combat 

### ISSUE THREAD

**Issue by Fortise** [wrathion-classic/Wrathion#5]
**Description:**
 https://www.wowhead.com/wotlk/quest=863/the-escape
Wizzlecrank's Shredder does not trigger the quest failed state when dying, does not assist player in combat, only retaliates its own mob aggro

**How to reproduce:**
Complete prequest 858 Ignition then accept The Escape, try to pull during the escort for assists, wait for the npc to die 

**How it should work:**
Upon death of any escort npcs the questlog should say (Failed)
not sure if the sound effect triggered either
NPC should engage upon player entering combat

https://www.youtube.com/watch?v=qj8BZmNnydk
video has joyous journeys and voice chat should be official

**Comment by wrathion-classic** [comment]
Fixed
