### ISSUE TITLE
Warlock Soul Drain Not working

### ISSUE THREAD

**Issue by Jinteki01** [wrathion-classic/Wrathion#6]
**Description:**
When casting Soul Drain, the animation occurs and initial mana is used but nothing happens. The character does not channel and no ticks of damage happen, but the mob does get put into combat. Nothing is shown in the combat log as well.

**How to reproduce:**
Make a warlock with Soul Drain learned.
Attempt to cast it on any attack-able mob.

**How it should work:**
The character should begin channeling damage on the mob for the duration of the spell.

**Comment by wrathion-classic** [comment]
Fixed.
