### ISSUE TITLE
Warlock's Curse of Agony not appying correctly

### ISSUE THREAD

**Issue by Jinteki01** [wrathion-classic/Wrathion#7]
**Description:**
Warlock's Curse of Agony is not applying to mobs who already have a damage-over-time (DoT) effect on them. It works properly when cast as the first DoT, but then fails to apply if any other DoT is already present. I've checked this with both Immolate and Corruption. Weirdly though this does not occur with rank 1 Immolate, but starts happening with rank 2 Immolate.

**How to reproduce:**
Apply rank 2 Immolate or any rank of Corruption to a mob.
Attempt to cast Curse of Agony on the same mob.

**How it should work:**
Curse of Agony should just be applied to the mob like any other DoT with no restriction regarding previously applied DoTs.

**Comment by Jinteki01** [comment]
Tested again with a mage's fireball DoT on the same mob. I could successfully put Curse of Agony on a mob while both in and out of a party with the mage. Just seems to be an issue with Corruption and rank 2 (or higher?) Immolate.

**Comment by wrathion-classic** [comment]
Fixed.
