### ISSUE TITLE
Paladin - Wrong version of Seal of Righteousness

### ISSUE THREAD

**Issue by MarkCech7** [wrathion-classic/Wrathion#8]
**Description:**
Paladin has wrong version of Seal of Righteousness upon creating character which is missing judgements tooltip, this one: [https://www.wowhead.com/wotlk/spell=20154/seal-of-righteousness]().

**How to reproduce:**
Create paladin character and open spellbook. (Also I noticed that second action bar button, where seal should be when you log into game is empty).

**How it should work:**
Paladin should have this version of seal in spellbook: [https://www.wowhead.com/wotlk/spell=21084/seal-of-righteousness](url).

![WoWScrnShot_111724_091220](https://github.com/user-attachments/assets/ec45a0b9-af82-4635-a380-fb227dc8e69c)

**Comment by lineagedr** [comment]
Invalid. 

https://www.youtube.com/watch?v=h8Kv5RNNnJs&t=776s
https://www.youtube.com/watch?v=l7w-yhhtIHk&t=15s

The spell not being on the action bar has been fixed.

**Comment by wrathion-classic** [comment]
Invalid. 

https://www.youtube.com/watch?v=h8Kv5RNNnJs&t=776s
https://www.youtube.com/watch?v=l7w-yhhtIHk&t=15s

The spell not being on the action bar has been fixed.

**Comment by wrathion-classic** [comment]
I'll investigate further.

**Comment by wrathion-classic** [comment]
Fixed
